// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqCcF2_inZlWBZJxZ4DQW0ihMReBc_2T0',
    appId: '1:974581832991:web:6fbca060c39b9cb015242a',
    messagingSenderId: '974581832991',
    projectId: 'plants-app-a93b3',
    authDomain: 'plants-app-a93b3.firebaseapp.com',
    storageBucket: 'plants-app-a93b3.appspot.com',
    measurementId: 'G-2L91V1NS2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl8mTYaJzyEq5QtscSSWUdgQB7utZhMeU',
    appId: '1:974581832991:android:e3eb253769c68e6415242a',
    messagingSenderId: '974581832991',
    projectId: 'plants-app-a93b3',
    storageBucket: 'plants-app-a93b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjAS_hftrHiOUDCpq1n1OWukPc2TX4mE0',
    appId: '1:974581832991:ios:95a0fd279dd0697515242a',
    messagingSenderId: '974581832991',
    projectId: 'plants-app-a93b3',
    storageBucket: 'plants-app-a93b3.appspot.com',
    iosBundleId: 'com.example.flowerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjAS_hftrHiOUDCpq1n1OWukPc2TX4mE0',
    appId: '1:974581832991:ios:95a0fd279dd0697515242a',
    messagingSenderId: '974581832991',
    projectId: 'plants-app-a93b3',
    storageBucket: 'plants-app-a93b3.appspot.com',
    iosBundleId: 'com.example.flowerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqCcF2_inZlWBZJxZ4DQW0ihMReBc_2T0',
    appId: '1:974581832991:web:6247719a178888f315242a',
    messagingSenderId: '974581832991',
    projectId: 'plants-app-a93b3',
    authDomain: 'plants-app-a93b3.firebaseapp.com',
    storageBucket: 'plants-app-a93b3.appspot.com',
    measurementId: 'G-5GJYYS0E14',
  );
}
